/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeambuilderRouteImport } from './routes/teambuilder'
import { Route as SpeedGearingRouteImport } from './routes/speed-gearing'
import { Route as AdventRouteImport } from './routes/advent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroHeroNameRouteImport } from './routes/hero.$heroName'

const TeambuilderRoute = TeambuilderRouteImport.update({
  id: '/teambuilder',
  path: '/teambuilder',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedGearingRoute = SpeedGearingRouteImport.update({
  id: '/speed-gearing',
  path: '/speed-gearing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventRoute = AdventRouteImport.update({
  id: '/advent',
  path: '/advent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroHeroNameRoute = HeroHeroNameRouteImport.update({
  id: '/hero/$heroName',
  path: '/hero/$heroName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advent': typeof AdventRoute
  '/speed-gearing': typeof SpeedGearingRoute
  '/teambuilder': typeof TeambuilderRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advent': typeof AdventRoute
  '/speed-gearing': typeof SpeedGearingRoute
  '/teambuilder': typeof TeambuilderRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advent': typeof AdventRoute
  '/speed-gearing': typeof SpeedGearingRoute
  '/teambuilder': typeof TeambuilderRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advent'
    | '/speed-gearing'
    | '/teambuilder'
    | '/hero/$heroName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advent' | '/speed-gearing' | '/teambuilder' | '/hero/$heroName'
  id:
    | '__root__'
    | '/'
    | '/advent'
    | '/speed-gearing'
    | '/teambuilder'
    | '/hero/$heroName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventRoute: typeof AdventRoute
  SpeedGearingRoute: typeof SpeedGearingRoute
  TeambuilderRoute: typeof TeambuilderRoute
  HeroHeroNameRoute: typeof HeroHeroNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teambuilder': {
      id: '/teambuilder'
      path: '/teambuilder'
      fullPath: '/teambuilder'
      preLoaderRoute: typeof TeambuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed-gearing': {
      id: '/speed-gearing'
      path: '/speed-gearing'
      fullPath: '/speed-gearing'
      preLoaderRoute: typeof SpeedGearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advent': {
      id: '/advent'
      path: '/advent'
      fullPath: '/advent'
      preLoaderRoute: typeof AdventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/$heroName': {
      id: '/hero/$heroName'
      path: '/hero/$heroName'
      fullPath: '/hero/$heroName'
      preLoaderRoute: typeof HeroHeroNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventRoute: AdventRoute,
  SpeedGearingRoute: SpeedGearingRoute,
  TeambuilderRoute: TeambuilderRoute,
  HeroHeroNameRoute: HeroHeroNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
